CREATE DATABASE IF NOT EXISTS ecommerce;
USE ecommerce;
CREATE TABLE IF NOT EXISTS orders (id BIGINT PRIMARY KEY, user_id BIGINT NOT NULL, created_at DATETIME(3) NOT NULL) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS payments (id BIGINT PRIMARY KEY, order_id BIGINT NOT NULL, amount_cent BIGINT NOT NULL, status VARCHAR(16) NOT NULL, paid_at DATETIME(3) NOT NULL, INDEX idx_order(order_id)) ENGINE=InnoDB;
